version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "Build phase - do your actual app build here if needed"
      - mkdir -p build
      - echo "<html><body><h1>Hello from CodeDeploy</h1></body></html>" > build/index.html

artifacts:
  files:
    - package.json
    - appspec.yml
    - scripts/**       # include both before_install.sh and after_install.sh
    - build/**         # your build output (like index.html)
